---
title: "Using Slack"
output: html_document
---

# How to use Slack, and for what

Slack is the main forum for BIOL 4110 for discussion between students, TA, and the instructor. Students will be given the Slack invite link at the beginning of the semester.

We prefer Slack for all communications but in some cases you can email us instead. 

The teaching team can’t guarantee that they will be able to respond to student messages outside of typical workday hours (0900-1700 ET). So, please be mindful of a 17:00 ET cutoff on Fridays when asking assignment-related questions.

### Use the _#general_ channel for most communications

The TA, instructor, and other students can participate and benefit from these conversations. Examples of appropriate topics for _#general_ are described below:

#### Clarifying concepts from lectures

Examples: 

> What's the difference between a `tibble` and a `data.frame`?

> Does `set.seed()` work on all computers (OS) and versions of R?

> Is there a difference between `[]` and `[[]]`?

#### Asking about course organization

e.g. the syllabus, course policies, assignment deadlines...

Examples:

> When is the deadline for Worksheet 1?

> For next lecture on Tuesday, are we going to be reviewing the upcoming project?

#### Clarifying instructions in assignments and other deliverables

Ping the instructor or a TA (`@Name-of-TA-or-instructor`).

Examples:

> For assignment 1a, question 3, can I pick any character variable in my dataset or does it need to be one with 3 or more categories? @Victor

> For assignment 2, do I use the same dataset that I used in assignment 1?


#### When you are stuck and need help

On assignments, workshops, group projects.

Examples:

> For worksheet 4, question 2.1, I can't seem to get the correct answer. Here is my code:
>
> ```
> answer2.1 <- mtcars %>% 
>      nest(cyl) %>%
>      ...
> ```

> For assignment 3, I keep getting an error when installing the package `distplyr`. This is the code  and error message: `...code and errors...`

Post an appropriate amount of details to get the help you want. Ideally use [`reprex`](https://www.tidyverse.org/help/), but at minimum provide your code, and any error messages.

### When to message a TA or instructor privately

If you are still stuck **after** trying _#general_, then you can message the TA for more help. 

Example situations:

> "Hi Jelany, I posted in _#general_ for help, but I'm still stuck on question 2.1 of worksheet 4. Can I get some help to work through this?"

If the TA feels that your message is inappropriate for a private conversation (e.g. it might be helpful for other students to see), they may redirect you to posting in the _#general_ channel. 

#### When you have questions or concerns about your grades

Either post an issue on your homework repo (preferred), or contact the marking TA on slack.

*Only message instructor if you are still unsatistified with your grade, after talking with your TA*

#### When you need a deadline extension

Read the Course Grading Policies section of the BIOL 4110 Course Outline, then email instructor with a self-declaration to hash out the details. 

#### When there is conflict with another student in a group project

For example, when you feel that your partner is not pulling their weight.

# Other guidelines for using Slack

- Use [**threads**](https://slack.com/intl/en-ca/help/articles/115000769927-Use-threads-to-organize-discussions-) to keep conversations organized

- If posting code, use \`\`\` (backticks). It's way easier to read. Even better, use [`reprex`](https://www.tidyverse.org/help/)



#### Attribution:

Adapted from STAT 545 Slack [communication guidelines](https://stat545.stat.ubc.ca/slack_communication/)

